name: webml
channels:
  - conda-forge
  - defaults

dependencies:
  - tensorflow
  - jupyter
  - numpy
  - scikit-learn
  - pillow
  - python>=3.11
  - pip:
    - boto3
    - flask
    - flask_cors
    - gunicorn
    - python-dotenv
